### ISSUE TITLE
single robot simulation error: Waiting for the map

### ISSUE THREAD

**Issue by HIT-ArcReactor** [hikashi/TM-RRT_exploration_Simulation#1]
I tried to use these comments to run single robot simlulation .
In console one :

` $ roslaunch ros_3d_multitb3 single_tb3_house5.launch`
In console two:

` $ roslaunch tmrrt_exploration single_exploration.launch`

however, after i ran the second comment, it came an error:

_waiting for the boundary points to be calculated
[INFO] [1657769534.583521]: Waiting for the map_

and it was useless to point points on rviz.
I guess there are something wrong with robot frame. I tried to read the code and .launch file, but I can`t tell the difference.
so is there anyone have same problem? or what should i do ?
Thanks a lot!

**Comment by hikashi** [comment]
can you check whether the merged map and each robot's cost map is available in the rostopic?

**Comment by hikashi** [comment]
Also, probably I missed out on the TEB planner for the simulation.
can you refer to the following update?
[09f4686](https://github.com/hikashi/TM-RRT_exploration_Simulation/commit/09f4686cc385beb23ec611a9ade0b70d06d59a1b)

**Comment by HIT-ArcReactor** [comment]
of cource, I have updated already. There was nothing wrong while running trio_exploration.launch, but running single_exploration.launch have the problem i just described. so this really puzzled me.
is it ok in your simlulation env?
wait a min, i am checking the merge map and cost map rostopic.
thanks for your reply!

**Comment by HIT-ArcReactor** [comment]
The costmap works  correctly . But we don't seem to need merge map because we only have one robot

**Comment by hikashi** [comment]
Let me check on a newly setup environment and get back to you. 
Most of the simulations I have done focus on the multi-robot environment.

**Comment by hikashi** [comment]
Hi, 

I tried on my side and there is no issue with a single robot setting up the folder cleanly from Github.
Mainly I run the turtlebot3 simulation and give it like 5 seconds before running the tmrrt exploration launch file.
Can you provide me with at least a screen recording of how you ran the code so that I can troubleshoot/recreate a similar issue?

**Comment by HIT-ArcReactor** [comment]
1. setting up the folder cleanly from Github.
2. change the robot name(maybe this step has problems)
3. run
https://user-images.githubusercontent.com/88709393/178927692-cb1612d5-0df5-417f-b7fb-5dd8e0d5536d.mp4

**Comment by HIT-ArcReactor** [comment]
How did you run the launch files? Maybe I can try them on my side as well

**Comment by hikashi** [comment]
I have uploaded the amended single launch file and boundary file.
I think basically just the namespacing issue. It should have been /tb3_0/map instead of /map.

Kindly download the updated folder to run.

The way I run basically is the same as you, you may check the following video
https://youtu.be/qvQ6xvXSdWA

**Comment by HIT-ArcReactor** [comment]
Oh, it works!
Thanks for your patience，this is very helpful for a beginner.
Best wishes!!
